Repository Team-Submit/23-EMB-FE, pull requests merged in 2023-10, with the labels that each got.

#25 💄:: 검색 목록 페이지 모달 및 페이지네이션 추가
  src/components/common/SearchInput/style.ts
  src/pages/SearchList/index.tsx
  src/pages/SearchList/style.ts
Labels: publishing

#23 💄:: 업로드페이지 컴포넌트 분리 및 모달창 퍼블리싱
  src/components/common/UploadInput/index.tsx
  src/components/common/UploadInput/style.ts
  src/pages/Upload/index.tsx
Labels: publishing

#18 💄:: 내 정보 수정 페이지 퍼블리싱
  src/components/pages/my/password/index.tsx
  src/components/pages/my/password/style.ts
  src/components/pages/my/profile/index.tsx
  src/components/pages/my/profile/style.ts
Labels: publishing

#26 🔀 :: 디자인 시스템 수정
  src/components/common/Input/index.tsx
  src/components/common/InputAuto/style.ts
  src/components/common/Radio/style.ts
  src/pages/Search/style.ts
  src/styles/common/Button.ts
  src/styles/theme.ts
Labels: Design System

#19 💄:: admin page 퍼블리싱
  src/App.tsx
  src/pages/Admin/index.tsx
  src/pages/Admin/style.ts
Labels: publishing

#27 🔀 :: inputAuto api 연동
  src/apis/common/department.ts
  src/components/common/InputAuto/index.tsx
Labels: Design System

#31 🔀 :: radio 버튼 prop 추가
  src/components/common/Radio/index.tsx
  src/components/common/Radio/style.ts
Labels: Design System

#32 💄:: Radio 스타일 수정
  src/components/common/Radio/style.ts
Labels: Design System

#28 💄:: 모달창 활성화 및 비밀번호 확인 생성
  src/components/pages/my/password/index.tsx
  src/components/pages/my/password/style.ts
  src/components/pages/my/profile/index.tsx
  src/components/pages/my/profile/modal/index.tsx
  src/components/pages/my/profile/modal/style.ts
  src/components/pages/my/profile/style.ts
Labels: Publishing

#34 🔀 :: DepartmentInput 구현
  src/components/common/DepartmentInput/index.tsx
  src/components/common/InputAuto/index.tsx
  src/components/common/InputAuto/style.ts
Labels: Design System

#36 🚚 :: 파일 경로 수정
  src/pages/My/password/index.tsx
  src/pages/My/password/style.ts
  src/pages/My/profile/Modal/index.tsx
  src/pages/My/profile/Modal/style.ts
  src/pages/My/profile/index.tsx
  src/pages/My/profile/style.ts
Labels: Publishing

#37 💩:: 타입지정 폴더명 수정
  src/components/document/CerificationOfCareerPDF/index.tsx
  src/components/document/CerificationOfCareerPDF/style.ts
  src/components/document/FileDownloadModal/index.tsx
Labels: etc

#38 ✨ :: MY페이지 API 연동
  src/apis/my/index.tsx
  src/apis/my/my.type.ts
  src/pages/My/password/index.tsx
  src/pages/My/password/style.ts
  src/pages/My/profile/index.tsx
  src/pages/My/profile/style.ts
Labels: API Intigration

#43 ✨:: 모달 lowImportance 속성 추가
  src/components/common/Modal/index.tsx
Labels: Function

#42 ✨ :: 상세보기 페이지 api연동
  src/App.tsx
  src/apis/common/detail.ts
  src/components/common/DetailData/Last.tsx
  src/components/common/DetailData/Now.tsx
  src/components/common/DetailData/Work.tsx
  src/pages/Detail/index.tsx
Labels: API Intigration

#41 ✨ :: 검색 인풋 상태 관리 및 라우팅 추가
  src/components/common/SearchInput/index.tsx
Labels: Function

#40 ✨ :: 검색 리스트 페이지 개발 완성
  src/apis/common/searchList.ts
  src/components/common/SearchListModal/index.tsx
  src/components/common/SearchListModal/style.ts
  src/pages/SearchList/index.tsx
  src/pages/SearchList/style.ts
Labels: API Intigration

#39 ✨ :: 업로드페이지 수정
  src/apis/common/Upload.ts
  src/components/common/UploadInput/index.tsx
  src/components/common/UploadInput/style.ts
  src/components/common/UploadModal/index.tsx
  src/components/common/UploadModal/style.ts
Labels: API Intigration

#44 ✨:: api instance refresh token 재발급 코드 작성
  src/apis/index.ts
Labels: API Intigration
