Repository Team-Submit/23-EMB-FE, pull requests merged in 2023-09, with the labels that each got.

#1 :twisted_rightwards_arrows: :: 디자인 시스템
  src/assets/icons/Bar.tsx
  src/assets/icons/Check.tsx
  src/assets/icons/ChevronDown.tsx
  src/assets/icons/ChevronLeft.tsx
  src/assets/icons/DownLoad.tsx
  src/assets/icons/Exclamation.tsx
  src/assets/icons/Logo.png
  src/assets/icons/Plus.tsx
  src/assets/icons/Search_20.tsx
  src/assets/icons/Search_24.tsx
  src/components/common/Data/SearchData.tsx
  src/components/common/Data/UserData.tsx
  src/components/common/Data/index.tsx
  src/components/common/Data/style.ts
  src/components/common/DepartmentBadge/index.tsx
  src/components/common/DepartmentBadge/style.ts
  src/components/common/Header/index.tsx
  src/components/common/Header/style.ts
  src/components/common/Modal/index.tsx
  src/components/common/Modal/style.ts
  src/components/common/Tap/index.tsx
  src/components/common/Tap/style.ts
  src/styles/common/Button.ts
  src/styles/globalStyle.ts
  src/styles/theme.ts
  src/types/IconProps.ts
Labels: Design System

#2 🔀 :: 디자인시스템 header
  src/App.tsx
  src/assets/icons/Search20.tsx
  src/assets/icons/Search24.tsx
  src/components/common/Header/index.tsx
  src/components/common/Header/style.ts
  src/layouts/AppLayout/index.tsx
  src/layouts/AppLayout/style.ts
Labels: Design System

#3 💄:: Logo import 에러수정
  src/assets/index.ts
  src/declare.d.ts
Labels: bug

#4 :lipstick: :: input컴포넌트
  package.json
  src/components/common/Header/style.ts
  src/components/common/Input/index.tsx
  src/components/common/Input/style.ts
  src/components/common/InputAuto/index.tsx
  src/components/common/InputAuto/style.ts
  src/components/common/Modal/style.ts
  yarn.lock
Labels: Design System

#8 :twisted_rightwards_arrows: :: tab 컴포넌트 추가
  src/App.tsx
  src/components/common/Header/index.tsx
  src/components/common/Tab/EachTab/index.tsx
  src/components/common/Tab/index.tsx
  src/components/common/Tab/style.ts
Labels: Design System

#7 💄 :: 검색 페이지 퍼블리싱 완성
  src/components/common/SearchInput/index.tsx
  src/components/common/SearchInput/style.ts
  src/components/pages/Search/index.tsx
  src/components/pages/Search/style.ts
  src/pages/Search.tsx
Labels: publishing

#9 🔀 :: boxShadow style 추가
  src/styles/theme.ts
Labels: Design System

#13 🔀 :: 디자인 시스템 수정
  src/assets/icons/ChevronLeft20.tsx
  src/assets/icons/ChevronRight20.tsx
  src/assets/icons/Home20.tsx
  src/components/common/Data/UserData.tsx
  src/components/common/Data/style.ts
  src/styles/common/Button.ts
Labels: Design System

#15 💄:: 404 페이지 퍼블리싱
  src/App.tsx
  src/pages/NotFound/index.tsx
  src/pages/NotFound/style.ts
Labels: publishing

#14 🔀 :: 디자인 시스템 icon 수정
  src/assets/icons/ChevronRight20.tsx
  src/assets/icons/Home20.tsx
Labels: Design System

#20 💄:: Radio 추가 & Modal 수정
  src/components/common/Modal/index.tsx
  src/components/common/Modal/style.ts
  src/components/common/Pagination/index.tsx
  src/components/common/Radio/index.tsx
  src/components/common/Radio/style.ts
Labels: Design System
